expense_statements = [
    "I spent ₹250 on groceries today.",
    "Bought vegetables and fruits for ₹300.",
    "₹150 went for milk and bread this morning.",
    "Paid ₹500 for petrol yesterday.",
    "I refilled gas for ₹450 last week.",
    "Gave ₹100 for the watchman as a tip.",
    "Spent ₹1,200 on my electricity bill.",
    "Paid ₹2,000 for this month's rent.",
    "₹350 spent on my mobile recharge.",
    "Ordered biryani for ₹800 from Zomato.",
    "Took an auto ride, paid ₹120.",
    "Paid ₹200 for parking at the mall.",
    "Spent ₹2,500 on my kid's tuition fees.",
    "Bought a new t-shirt for ₹1,000.",
    "Purchased medicine for ₹300 at the pharmacy.",
    "Paid ₹100 for chai and snacks at a tapri.",
    "Lunch at a dhaba cost me ₹400.",
    "Spent ₹3,000 on my car's service.",
    "Recharged my metro card with ₹500.",
    "Paid ₹150 for a movie ticket.",
    "Ordered pizza for ₹700 last night.",
    "Spent ₹900 on a new pair of shoes.",
    "Paid ₹2,000 for broadband this month.",
    "I sent ₹5,000 to my parents yesterday.",
    "Spent ₹800 on stationary items for office work.",
    "Paid ₹1,500 to the plumber for repairs.",
    "Gave ₹50 to the beggar near the temple.",
    "₹700 went for a haircut and grooming.",
    "Paid ₹3,500 for a new smartphone cover and accessories.",
    "Booked a train ticket for ₹1,200.",
    "₹300 was spent on dosa and coffee at a restaurant.",
    "Bought a gift for ₹1,000 for my friend's wedding.",
    "Gave ₹1,200 as EMI for my bike loan.",
    "Paid ₹500 for dry cleaning my suits.",
    "Recharged my DTH with ₹350.",
    "Spent ₹1,700 on groceries and snacks for a house party.",
    "Bought a gold chain for ₹25,000 at Tanishq.",
    "Paid ₹1,000 for a doctor's consultation.",
    "Spent ₹250 on chocolates and snacks for kids.",
    "Paid ₹5,000 for this year's health insurance premium.",
    "₹750 went for maintenance charges of the apartment.",
    "Bought a new book for ₹450.",
    "Spent ₹2,800 on gym membership fees.",
    "Had pani puri at a stall, spent ₹80.",
    "Paid ₹15,000 as advance for my house rent.",
    "Spent ₹6,000 on travel bookings for an upcoming trip.",
    "Paid ₹3,000 for my cat's veterinary check-up.",
    "Bought new curtains for ₹1,200.",
    "Spent ₹500 on lottery tickets (just trying my luck!).",
    "Gave ₹200 to my maid for some extra work she did."
]